default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: schoolstatus_development

test:
  <<: *default
  database: schoolstatus_test

production:
  <<: *default
  database: schoolstatus_production
  # Uncomment the following lines to enable connection pooling and other production settings
  # url: <%= ENV['DATABASE_URL'] %>
  # sslmode: require
